# Ресстр источник
source_registry:
  url: http://localhost:5001
  # username: some_user
  # password: some_password

# Конечный реестр
destination_registry:
  url: http://localhost:5000

# Взять все репозитории из реестра
# Если False то нужно указать список в repositories
take_all_repositories: True

# Фильтр префиксов
prefixes: False

# Репозитории для синхронизации
repositories:
  # - registry
  - python

# Префиксы, которые ищутся в тегах для дальнейшей синхронизации
prefix:
  - "p_"
  - "d_"