# Ресстр источник
source_registry:
  url: https://images.boston.loc
  # username: some_user
  # password: some_password

# Конечный реестр
destination_registry:
  url: http://chicago.loc:5000

# Взять все репозитории из реестра
# Если False то нужно указать список в repositories
take_all_repositories: True

# Фильтр префиксов
prefixes: False

# Репозитории для синхронизации
repositories:
  # - registry
  - python

# Префиксы, которые ищутся в тегах для дальнейшей синхронизации
prefix:
  - "p_"

# Удаление репозиториев
delete_repositories: False